public class Resources {
    int timeDelay;
    Resources(){
    }


    public void chooseDifficulty(int timeDelay) throws InterruptedException {
        this.timeDelay = timeDelay;
        System.out.println("-------------------------------------------------------------------------------------------------------------------------------------------------");
        Thread.sleep(timeDelay);
        System.out.println("                    ______ _      _     __   __                ______ _  __  __ _            _   _ _         ");
        Thread.sleep(timeDelay);
        System.out.println("                    | ___ (_)    | |    \\ \\ / /                |  _  (_)/ _|/ _(_)          | | | | |        ");
        Thread.sleep(timeDelay);
        System.out.println("                    | |_/ /_  ___| | __  \\ V /___  _   _ _ __  | | | |_| |_| |_ _ _   _  ___| |_| | |_ _   _ ");
        Thread.sleep(timeDelay);
        System.out.println("                    |  __/| |/ __| |/ /   \\ // _ \\| | | | '__| | | | | |  _|  _| | | | |/ __| __| | __| | | |");
        Thread.sleep(timeDelay);
        System.out.println("                    | |   | | (__|   <    | | (_) | |_| | |    | |/ /| | | | | | | |_| | (__| |_| | |_| |_| |");
        Thread.sleep(timeDelay);
        System.out.println("                    \\_|   |_|\\___|_|\\_\\   \\_/\\___/ \\__,_|_|    |___/ |_|_| |_| |_|\\__,_|\\___|\\__|_|\\__|\\__, |");
        Thread.sleep(timeDelay);
        System.out.println("                                                                                                        __/ |");
        Thread.sleep(timeDelay);
        System.out.println("                                                                                                       |___/");
        Thread.sleep(timeDelay);
        System.out.println();
        Thread.sleep(timeDelay);
        System.out.println("                                            .-''-.     ____       .-'''-.    ____     __  ");
        Thread.sleep(timeDelay);
        System.out.println("                                          .'_ _   \\  .'  __ `.   / _     \\   \\   \\   /  / ");
        Thread.sleep(timeDelay);
        System.out.println("                                         / ( ` )   '/   '  \\  \\ (`' )/`--'    \\  _. /  '  ");
        Thread.sleep(timeDelay);
        System.out.println("                                        . (_ o _)  ||___|  /  |(_ o _).        _( )_ .'   ");
        Thread.sleep(timeDelay);
        System.out.println("                                        |  (_,_)___|   _.-`   | (_,_). '.  ___(_ o _)' ");
        Thread.sleep(timeDelay);
        System.out.println("                                        '  \\   .---..'   _    |.---.  \\  :|   |(_,_)'  ");
        Thread.sleep(timeDelay);
        System.out.println("                                         \\  `-'    /|  _( )_  |\\    `-'  ||   `-'  /      ");
        Thread.sleep(timeDelay);
        System.out.println("                                          \\       / \\ (_ o _) / \\       /  \\      /    ");
        Thread.sleep(timeDelay);
        System.out.println("                                           `'-..-'   '.(_,_).'   `-...-'    `-..-'        ");
        Thread.sleep(timeDelay);
        System.out.println("                                    ____    ____              __   _                                            ");
        Thread.sleep(timeDelay);
        System.out.println("                                   |_   \\  /   _|            |  ] (_)                                           ");
        Thread.sleep(timeDelay);
        System.out.println("                                     |   \\/   |  .---.   .--.| |  __  __   _   _ .--..--.                       ");
        Thread.sleep(timeDelay);
        System.out.println("                                     | |\\  /| | / /__\\\\/ /'`\\' | [  |[  | | | [ `.-. .-. |                      ");
        Thread.sleep(timeDelay);
        System.out.println("                                    _| |_\\/_| |_| \\__.,| \\__/  |  | | | \\_/ |, | | | | | |                      ");
        Thread.sleep(timeDelay);
        System.out.println("                                   |_____||_____|'.__.' '.__.;__][___]'.__.'_/[___||__||__]                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                                 _   _               _                     ");
        Thread.sleep(timeDelay);
        System.out.println("                                                | | | |             | |                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                                | |_| | __ _ _ __ __| |                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                                |  _  |/ _` | '__/ _` |                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                                | | | | (_| | | | (_| |                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                                \\_| |_/\\__,_|_|  \\__,_|                    ");
        Thread.sleep(timeDelay);
        System.out.println("-------------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println();
        System.out.println();
        System.out.println();

    }

    public void intro(int timeDelay) throws InterruptedException{
        System.out.println("-------------------------------------------------------------------------------------------------------------------------------------------------");
        Thread.sleep(timeDelay);
        System.out.println("                  ,'\\ ");
        Thread.sleep(timeDelay);
        System.out.println("                  _.----.        ____         ,'  _\\   ___    ___     ____");
        Thread.sleep(timeDelay);
        System.out.println("              _,-'       `.     |    |  /`.   \\,-\'    |   \\  /   |   |    \\  |`.");
        Thread.sleep(timeDelay);
        System.out.println("              \\      __    \\    '-.  | /   `.  ___    |    \\/    |   '-.   \\ |  |");
        Thread.sleep(timeDelay);
        System.out.println("               \\.    \\ \\   |  __  |  |/    ,','_  `.  |          | __  |    \\|  |");
        Thread.sleep(timeDelay);
        System.out.println("                 \\    \\/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |");
        Thread.sleep(timeDelay);
        System.out.println("                  \\     ,-'/  /   \\    ,'   | \\/ / ,`.|         /  /   \\  |     |");
        Thread.sleep(timeDelay);
        System.out.println("                   \\    \\ |   \\_/  |   `-.  \\    `'  /|  |    ||   \\_/  | |\\    |");
        Thread.sleep(timeDelay);
        System.out.println("                    \\    \\ \\      /       `-.`.___,-' |  |\\  /| \\      /  | |   |");
        Thread.sleep(timeDelay);
        System.out.println("                     \\    \\ `.__,'|  |`-._    `|      |__| \\/ |  `.__,'|  | |   |");
        Thread.sleep(timeDelay);
        System.out.println("                      \\_.-'       |__|    `-._ |              '-.|     '-.| |   |");
        Thread.sleep(timeDelay);
        System.out.println("                                              `'                            '-._|");
        Thread.sleep(timeDelay);
        System.out.println("-------------------------------------------------------------------------------------------------------------------------------------------------");

    }
    
    public void pickYourPokemonPlayerOnePicture(int timeDelay) throws InterruptedException{
        System.out.println("Choose Your Pokemon");
        System.out.println("-------------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("              _.--\"\"`-..                                                                                   _,........__                                                 ");
        Thread.sleep(timeDelay);
        System.out.println("            ,'          `.                                                                             ,-'            \"`-.                                              ");
        Thread.sleep(timeDelay);
        System.out.println("          ,'          __  `.                                                                          ,'                   `-.                                          ");
        Thread.sleep(timeDelay);
        System.out.println("         /|          \" __   \\                                                                       ,'                        \\                                         ");
        Thread.sleep(timeDelay);
        System.out.println("        , |           / |.   .                                                                    ,'                           .                                        ");
        Thread.sleep(timeDelay);
        System.out.println("        |,'          !_.'|   |                                                                    .'\\               ,\"\".       `                                        ");
        Thread.sleep(timeDelay);
        System.out.println("      ,'             '   |   |                                                                   ._.'|             / |  `       \\                                       ");
        Thread.sleep(timeDelay);
        System.out.println("     /              |`--'|   |                                                                   |   |            `-.'  ||       `.                                     ");
        Thread.sleep(timeDelay);
        System.out.println("    |                `---'   |                                                                   |   |            '-._,'||       | \\                                    ");
        Thread.sleep(timeDelay);
        System.out.println("     .   ,                   |                       ,\".                                         .`.,'             `..,'.'       , |`-.                                 ");
        Thread.sleep(timeDelay);
        System.out.println("      ._     '           _'  |                    , ' \\ `                                        l                       .'`.  _/  |   `.                               ");
        Thread.sleep(timeDelay);
        System.out.println("  `.. `.`-...___,...---\"\"    |       __,.        ,`\"   L,|                                       `-.._'-   ,          _ _'   -\" \\  .     `                              ");
        Thread.sleep(timeDelay);
        System.out.println("  |, `- .`._        _,-,.'   .  __.-'-. /        .   ,    \\                                 `.\"\"\"\"\"'-.`-...,---------','         `. `....__.                            ");
        Thread.sleep(timeDelay);
        System.out.println("-:..     `. `-..--_.,.<       `\"      / `.        `-/ |   .                                 .'        `\"-..___      __,'\\          \\  \\     \\                           ");
        Thread.sleep(timeDelay);
        System.out.println("  `,         \"\"\"\"'     `.              ,'         |   |  ',,                                \\_ .          |   `\"\"\"\"'    `.           . \\     \\                          ");
        Thread.sleep(timeDelay);
        System.out.println("    `.      '            '            /          '    |'. |/                                   `.          |              `.          |  .     L                        ");
        Thread.sleep(timeDelay);
        System.out.println("    `.      '            '            /          '    |'. |/                                   `.          |              `.          |  .     L                        ");
        Thread.sleep(timeDelay);
        System.out.println("        `._'               \\   '\"\\                .      |                                         `._    .'      |          `.     .|   ,     |                        ");
        Thread.sleep(timeDelay);
        System.out.println("           |                '     \\                `._  ,'                                            `--,\\       .            `7\"\"' |  ,      |                        ");
        Thread.sleep(timeDelay);
        System.out.println("           |                 '     \\                 .'|                                                 ` `      `            /     |  |      |    _,-'\"\"\"`-.          ");
        Thread.sleep(timeDelay);
        System.out.println("           |                 .      \\                | |                                                  \\ `.     .          /      |  '      |  ,'          `.        ");
        Thread.sleep(timeDelay);
        System.out.println("           |                 |       L              ,' |                                                   \\  v.__  .        '       .   \\    /| /              \\      ");
        Thread.sleep(timeDelay);
        System.out.println("           `                 |       |             /   '                                                    \\/    `\"\"\\\"\"\"\"\"\"\"`.       \\   \\  /.''                |     ");
        Thread.sleep(timeDelay);
        System.out.println("            \\                |       |           ,'   /                                                      `        .        `._ ___,j.  `/ .-       ,---.     |     ");
        Thread.sleep(timeDelay);
        System.out.println("          ,' \\               |  _.._ ,-..___,..-'    ,'                                            /         ,`-.      \\         .\"     `.  |/        j     `    |     ");
        Thread.sleep(timeDelay);
        System.out.println("         /     .             .      `!             ,j'                                              /       /    `.     \\       /         \\ /         |     /    j     ");
        Thread.sleep(timeDelay);
        System.out.println("        /       `.          /        .           .'/                       _,.------....___,.' ',.-.       |       `-.   7-.._ .          |\"          '         /      ");
        Thread.sleep(timeDelay);
        System.out.println("       .          `.       /         |        _.'.'                     ,-'          _,.--\"        |       |          `./_    `|          |            .     _,'       ");
        Thread.sleep(timeDelay);
        System.out.println("        `.          7`'---'          |------\"'_.'                     ,'         _.-'              .       `.           / `----|          |-............`---'          ");
        Thread.sleep(timeDelay);
        System.out.println("       _,.`,_     _'                ,''-----\"'                       /   ,     ,'                   `        \\          \\      |          |                            ");
        Thread.sleep(timeDelay);
        System.out.println("   _,-_    '       `.     .'      ,\\                                .   /     /                     ``.     ,'           )     `.         |                            ");
        Thread.sleep(timeDelay);
        System.out.println("   -\" /`.         _,'     | _  _  _.|                               |  |     .                       \\.\\     7____,,..--'      /          |                            ");
        Thread.sleep(timeDelay);
        System.out.println("    \"\"--'---\"\"\"\"\"'        `' '! |! /                      ____      |___._.  |       __               \\ `.                     `---.__,--.'                            ");
        Thread.sleep(timeDelay);
        System.out.println("                            `\" \" -'                     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\                                                            ");
        Thread.sleep(timeDelay);
        System.out.println("                                                    .  ,            __               `              |   .                                                              ");
        Thread.sleep(timeDelay);
        System.out.println("                                                  `,'         ,-\"'  .               \\             |    L                                                               ");
        Thread.sleep(timeDelay);
        System.out.println("                                                  ,'          '    _.'                -._          /    |                                                              ");
        Thread.sleep(timeDelay);
        System.out.println("                                                 ,`-.    ,\".   `--'                      >.      ,'     |                                                              ");
        Thread.sleep(timeDelay);
        System.out.println("                                               . .'\\'   `-'       __    ,  ,-.         /  `.__.-      ,'                                                               ");
        Thread.sleep(timeDelay);
        System.out.println("                                               ||:, .           ,'  ;  /  / \\ `        `.    .      .'/                                                                ");
        Thread.sleep(timeDelay);
        System.out.println("                                                j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , /                                                                ");
        Thread.sleep(timeDelay);
        System.out.println("                                             / L:_  |                 .  \"' :_;                `.'.'                                                                   ");
        Thread.sleep(timeDelay);
        System.out.println("                                              .    \"\"'                  \"\"\"\"\"'                    V                                                                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                              `.                                 .    `.   _,..  `                                                                     ");
        Thread.sleep(timeDelay);
        System.out.println("                                                `,_   .    .                _,-'/    .. `,'   __  `                                                                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                                  ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  .                                                                  ");
        Thread.sleep(timeDelay);
        System.out.println("                                                /   `. \"`-.--\"'         _,' ,'     `---' |    `./  |                                                                   ");
        Thread.sleep(timeDelay);
        System.out.println("                                               .   _  `\"\"'--.._____..--\"   ,             '         |                                                                   ");
        Thread.sleep(timeDelay);
        System.out.println("                                               | .\" `. `-.                /-.           /          ,                                                                   ");
        Thread.sleep(timeDelay);
        System.out.println("                                               | `._.'    `,_            ;  /         ,'          .                                                                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                                .'          /| `-.        . ,'         ,           ,                                                                   ");
        Thread.sleep(timeDelay);
        System.out.println("                                                '-.__ __ _,','    '`-..___;-...__   ,.'\\ ____.___.'                                                                    ");
        Thread.sleep(timeDelay);
        System.out.println("                                               `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--'                                                                      ");
        Thread.sleep(timeDelay);
        System.out.println("");
        System.out.println("-------------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("                      Charmander                                                                             Squirtle                  ");
        System.out.println("                                                                  Bulbasaur                                                     ");
        System.out.print("                              Choose Your Pokemon :   ");
    }

    public void pickYourPokemonPlayerTwoPicture(int timeDelay) throws InterruptedException{
        System.out.println("PLayer 2 // Opponent Picture");
    }
}
